export const mockUser = {
  login: 'manishwild',
  id: 57616810,
  node_id: 'MDQ6VXNlcjU3NjE2ODEw',
  avatar_url: 'https://avatars.githubusercontent.com/u/57616810?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/manishwild',
  html_url: 'https://github.com/manishwild',
  followers_url: 'https://api.github.com/users/manishwild/followers',
  following_url:
    'https://api.github.com/users/manishwild/following{/other_user}',
  gists_url: 'https://api.github.com/users/manishwild/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/manishwild/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/manishwild/subscriptions',
  organizations_url: 'https://api.github.com/users/manishwild/orgs',
  repos_url: 'https://api.github.com/users/manishwild/repos',
  events_url: 'https://api.github.com/users/manishwild/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/manishwild/received_events',
  type: 'User',
  site_admin: false,
  name: 'Manish Khadgi Shahi',
  company: null,
  blog: '',
  location: 'hamburg',
  email: null,
  hireable: null,
  bio: 'I am a Web Developer who loves coding, solving problems, and overcoming challenges. I am always curious about the latest tools used with best practices and love',
  twitter_username: null,
  public_repos: 37,
  public_gists: 0,
  followers: 3,
  following: 5,
  created_at: '2019-11-11T08:10:35Z',
  updated_at: '2022-07-21T15:07:00Z',
}
